import type { ComponentProps } from "solid-js";
export type ButtonProps = {
    classList?: any;
    class?: string;
    link?: string;
    type?: 'primary' | 'success' | 'error' | 'warning' | 'default' | 'dashed' | 'link' | 'text';
    block?: boolean;
    size?: 'small' | 'default' | 'large';
    active?: boolean;
    circle?: boolean;
    round?: boolean;
    disabled?: boolean;
    loading?: boolean;
    ghost?: boolean;
    icon?: any;
    danger?: boolean;
    iconAlign?: 'left' | 'right';
    ref?: any;
    onClick?: (e: any) => void;
} & ComponentProps<any>;
export declare const Button: (props: ButtonProps) => import("solid-js").JSX.Element;
