export * from './Option';
export * from './OptionGroup';
type SelectOptions = {
    name?: string;
    value?: any;
    disabled?: boolean;
    size?: 'small' | 'large';
    clearable?: boolean;
    multi?: boolean;
    prefix?: any;
    style?: any;
    placeholder?: string;
    data?: Array<any>;
    textField?: string;
    valueField?: string;
    class?: any;
    classList?: any;
    filter?: boolean;
    renderOption?: Function;
    ref?: any;
    emptyOption?: any;
    onChange?: Function;
    showMax?: number;
    valueClosable?: boolean;
    transfer?: boolean;
    align?: 'bottomLeft' | 'bottomRight';
    showMore?: boolean;
    loading?: boolean;
    children?: any;
    remoteMethod?: Function;
    maxHeight?: number;
    debounceTime?: number;
    defaultLabel?: string | string[];
};
export declare function Select(props: SelectOptions): import("solid-js").JSX.Element;
