import { JSXElement } from "solid-js";
type TableProps = {
    columns: any[];
    data: any[];
    height?: number;
    classList?: any;
    class?: any;
    style?: any;
    border?: boolean;
    stripe?: boolean;
    highlight?: boolean;
    onRowSelect?: Function;
    onRowChecked?: Function;
    onCheckedAll?: Function;
    onSort?: Function;
    ref?: any;
    size?: 'small';
    spanMethod?: Function;
    loading?: boolean;
};
export type TableStore = {
    columns: ColumnProps[];
    data: any[];
    showFixedLeft: boolean;
    showFixedRight: boolean;
    checkedAll: boolean | string;
    resizing: boolean;
    x: number;
    posX: number;
    startX: number;
    resizeId?: string;
};
export type ColumnProps = {
    name?: string;
    title?: string | JSXElement;
    render?: Function;
    type?: string;
    width?: string;
    resize?: boolean;
    sort?: boolean | 'custom';
    sortMethod?: Function;
    sortType?: 'asc' | 'desc' | '';
    fixed?: 'left' | 'right';
    tree?: boolean;
    fixedLeftLast?: boolean;
    fixedRightFirst?: boolean;
    id: string;
    _index: number;
    _: string;
};
export declare function Table(props: TableProps): import("solid-js").JSX.Element;
export declare const useTableContext: () => unknown;
export {};
