type UploadProps = {
    multiple?: boolean;
    webkitdirectory?: boolean;
    accept?: string;
    classList?: any;
    class?: string;
    style?: any;
    disabled?: boolean;
    children?: any;
    beforeUpload?: Function;
    format?: string[];
    maxSize?: number;
    name?: string;
    headers?: any;
    withCredentials?: boolean;
    data?: any;
    action?: string;
    onProgress?: Function;
    onSuccess?: Function;
    onError?: Function;
    onRemove?: Function;
    onPreview?: Function;
    onFormatError?: Function;
    onExceededSize?: Function;
    onClear?: Function;
    defaultFileList?: any[];
    type?: 'select' | 'drag';
    paste?: boolean;
    getFileUrl?: Function;
    ref?: any;
    listType?: 'picture';
};
export declare function Upload(props: UploadProps): import("solid-js").JSX.Element;
export {};
