import type { ComponentProps, JSX } from "solid-js";
export declare function useClassList(props: ComponentProps<any>, ...customClassList: any): any;
export declare function useStyle(props: any | ComponentProps<'div'>, customStyle: JSX.CSSProperties): {
    [x: `-${string}`]: string | number | undefined;
    "accent-color"?: import("csstype").Property.AccentColor | undefined;
    "align-content"?: import("csstype").Property.AlignContent | undefined;
    "align-items"?: import("csstype").Property.AlignItems | undefined;
    "align-self"?: import("csstype").Property.AlignSelf | undefined;
    "align-tracks"?: import("csstype").Property.AlignTracks | undefined;
    "animation-composition"?: import("csstype").Property.AnimationComposition | undefined;
    "animation-delay"?: import("csstype").Property.AnimationDelay<string & {}> | undefined;
    "animation-direction"?: import("csstype").Property.AnimationDirection | undefined;
    "animation-duration"?: import("csstype").Property.AnimationDuration<string & {}> | undefined;
    "animation-fill-mode"?: import("csstype").Property.AnimationFillMode | undefined;
    "animation-iteration-count"?: import("csstype").Property.AnimationIterationCount | undefined;
    "animation-name"?: import("csstype").Property.AnimationName | undefined;
    "animation-play-state"?: import("csstype").Property.AnimationPlayState | undefined;
    "animation-timeline"?: import("csstype").Property.AnimationTimeline | undefined;
    "animation-timing-function"?: import("csstype").Property.AnimationTimingFunction | undefined;
    appearance?: import("csstype").Property.Appearance | undefined;
    "aspect-ratio"?: import("csstype").Property.AspectRatio | undefined;
    "backdrop-filter"?: import("csstype").Property.BackdropFilter | undefined;
    "backface-visibility"?: import("csstype").Property.BackfaceVisibility | undefined;
    "background-attachment"?: import("csstype").Property.BackgroundAttachment | undefined;
    "background-blend-mode"?: import("csstype").Property.BackgroundBlendMode | undefined;
    "background-clip"?: import("csstype").Property.BackgroundClip | undefined;
    "background-color"?: import("csstype").Property.BackgroundColor | undefined;
    "background-image"?: import("csstype").Property.BackgroundImage | undefined;
    "background-origin"?: import("csstype").Property.BackgroundOrigin | undefined;
    "background-position-x"?: import("csstype").Property.BackgroundPositionX<0 | (string & {})> | undefined;
    "background-position-y"?: import("csstype").Property.BackgroundPositionY<0 | (string & {})> | undefined;
    "background-repeat"?: import("csstype").Property.BackgroundRepeat | undefined;
    "background-size"?: import("csstype").Property.BackgroundSize<0 | (string & {})> | undefined;
    "block-overflow"?: import("csstype").Property.BlockOverflow | undefined;
    "block-size"?: import("csstype").Property.BlockSize<0 | (string & {})> | undefined;
    "border-block-color"?: import("csstype").Property.BorderBlockColor | undefined;
    "border-block-end-color"?: import("csstype").Property.BorderBlockEndColor | undefined;
    "border-block-end-style"?: import("csstype").Property.BorderBlockEndStyle | undefined;
    "border-block-end-width"?: import("csstype").Property.BorderBlockEndWidth<0 | (string & {})> | undefined;
    "border-block-start-color"?: import("csstype").Property.BorderBlockStartColor | undefined;
    "border-block-start-style"?: import("csstype").Property.BorderBlockStartStyle | undefined;
    "border-block-start-width"?: import("csstype").Property.BorderBlockStartWidth<0 | (string & {})> | undefined;
    "border-block-style"?: import("csstype").Property.BorderBlockStyle | undefined;
    "border-block-width"?: import("csstype").Property.BorderBlockWidth<0 | (string & {})> | undefined;
    "border-bottom-color"?: import("csstype").Property.BorderBottomColor | undefined;
    "border-bottom-left-radius"?: import("csstype").Property.BorderBottomLeftRadius<0 | (string & {})> | undefined;
    "border-bottom-right-radius"?: import("csstype").Property.BorderBottomRightRadius<0 | (string & {})> | undefined;
    "border-bottom-style"?: import("csstype").Property.BorderBottomStyle | undefined;
    "border-bottom-width"?: import("csstype").Property.BorderBottomWidth<0 | (string & {})> | undefined;
    "border-collapse"?: import("csstype").Property.BorderCollapse | undefined;
    "border-end-end-radius"?: import("csstype").Property.BorderEndEndRadius<0 | (string & {})> | undefined;
    "border-end-start-radius"?: import("csstype").Property.BorderEndStartRadius<0 | (string & {})> | undefined;
    "border-image-outset"?: import("csstype").Property.BorderImageOutset<0 | (string & {})> | undefined;
    "border-image-repeat"?: import("csstype").Property.BorderImageRepeat | undefined;
    "border-image-slice"?: import("csstype").Property.BorderImageSlice | undefined;
    "border-image-source"?: import("csstype").Property.BorderImageSource | undefined;
    "border-image-width"?: import("csstype").Property.BorderImageWidth<0 | (string & {})> | undefined;
    "border-inline-color"?: import("csstype").Property.BorderInlineColor | undefined;
    "border-inline-end-color"?: import("csstype").Property.BorderInlineEndColor | undefined;
    "border-inline-end-style"?: import("csstype").Property.BorderInlineEndStyle | undefined;
    "border-inline-end-width"?: import("csstype").Property.BorderInlineEndWidth<0 | (string & {})> | undefined;
    "border-inline-start-color"?: import("csstype").Property.BorderInlineStartColor | undefined;
    "border-inline-start-style"?: import("csstype").Property.BorderInlineStartStyle | undefined;
    "border-inline-start-width"?: import("csstype").Property.BorderInlineStartWidth<0 | (string & {})> | undefined;
    "border-inline-style"?: import("csstype").Property.BorderInlineStyle | undefined;
    "border-inline-width"?: import("csstype").Property.BorderInlineWidth<0 | (string & {})> | undefined;
    "border-left-color"?: import("csstype").Property.BorderLeftColor | undefined;
    "border-left-style"?: import("csstype").Property.BorderLeftStyle | undefined;
    "border-left-width"?: import("csstype").Property.BorderLeftWidth<0 | (string & {})> | undefined;
    "border-right-color"?: import("csstype").Property.BorderRightColor | undefined;
    "border-right-style"?: import("csstype").Property.BorderRightStyle | undefined;
    "border-right-width"?: import("csstype").Property.BorderRightWidth<0 | (string & {})> | undefined;
    "border-spacing"?: import("csstype").Property.BorderSpacing<0 | (string & {})> | undefined;
    "border-start-end-radius"?: import("csstype").Property.BorderStartEndRadius<0 | (string & {})> | undefined;
    "border-start-start-radius"?: import("csstype").Property.BorderStartStartRadius<0 | (string & {})> | undefined;
    "border-top-color"?: import("csstype").Property.BorderTopColor | undefined;
    "border-top-left-radius"?: import("csstype").Property.BorderTopLeftRadius<0 | (string & {})> | undefined;
    "border-top-right-radius"?: import("csstype").Property.BorderTopRightRadius<0 | (string & {})> | undefined;
    "border-top-style"?: import("csstype").Property.BorderTopStyle | undefined;
    "border-top-width"?: import("csstype").Property.BorderTopWidth<0 | (string & {})> | undefined;
    bottom?: import("csstype").Property.Bottom<0 | (string & {})> | undefined;
    "box-decoration-break"?: import("csstype").Property.BoxDecorationBreak | undefined;
    "box-shadow"?: import("csstype").Property.BoxShadow | undefined;
    "box-sizing"?: import("csstype").Property.BoxSizing | undefined;
    "break-after"?: import("csstype").Property.BreakAfter | undefined;
    "break-before"?: import("csstype").Property.BreakBefore | undefined;
    "break-inside"?: import("csstype").Property.BreakInside | undefined;
    "caption-side"?: import("csstype").Property.CaptionSide | undefined;
    "caret-color"?: import("csstype").Property.CaretColor | undefined;
    clear?: import("csstype").Property.Clear | undefined;
    "clip-path"?: import("csstype").Property.ClipPath | undefined;
    color?: import("csstype").Property.Color | undefined;
    "color-adjust"?: import("csstype").Property.PrintColorAdjust | undefined;
    "color-scheme"?: import("csstype").Property.ColorScheme | undefined;
    "column-count"?: import("csstype").Property.ColumnCount | undefined;
    "column-fill"?: import("csstype").Property.ColumnFill | undefined;
    "column-gap"?: import("csstype").Property.ColumnGap<0 | (string & {})> | undefined;
    "column-rule-color"?: import("csstype").Property.ColumnRuleColor | undefined;
    "column-rule-style"?: import("csstype").Property.ColumnRuleStyle | undefined;
    "column-rule-width"?: import("csstype").Property.ColumnRuleWidth<0 | (string & {})> | undefined;
    "column-span"?: import("csstype").Property.ColumnSpan | undefined;
    "column-width"?: import("csstype").Property.ColumnWidth<0 | (string & {})> | undefined;
    contain?: import("csstype").Property.Contain | undefined;
    content?: import("csstype").Property.Content | undefined;
    "content-visibility"?: import("csstype").Property.ContentVisibility | undefined;
    "counter-increment"?: import("csstype").Property.CounterIncrement | undefined;
    "counter-reset"?: import("csstype").Property.CounterReset | undefined;
    "counter-set"?: import("csstype").Property.CounterSet | undefined;
    cursor?: import("csstype").Property.Cursor | undefined;
    direction?: import("csstype").Property.Direction | undefined;
    display?: import("csstype").Property.Display | undefined;
    "empty-cells"?: import("csstype").Property.EmptyCells | undefined;
    filter?: import("csstype").Property.Filter | undefined;
    "flex-basis"?: import("csstype").Property.FlexBasis<0 | (string & {})> | undefined;
    "flex-direction"?: import("csstype").Property.FlexDirection | undefined;
    "flex-grow"?: import("csstype").Property.FlexGrow | undefined;
    "flex-shrink"?: import("csstype").Property.FlexShrink | undefined;
    "flex-wrap"?: import("csstype").Property.FlexWrap | undefined;
    float?: import("csstype").Property.Float | undefined;
    "font-family"?: import("csstype").Property.FontFamily | undefined;
    "font-feature-settings"?: import("csstype").Property.FontFeatureSettings | undefined;
    "font-kerning"?: import("csstype").Property.FontKerning | undefined;
    "font-language-override"?: import("csstype").Property.FontLanguageOverride | undefined;
    "font-optical-sizing"?: import("csstype").Property.FontOpticalSizing | undefined;
    "font-size"?: import("csstype").Property.FontSize<0 | (string & {})> | undefined;
    "font-size-adjust"?: import("csstype").Property.FontSizeAdjust | undefined;
    "font-smooth"?: import("csstype").Property.FontSmooth<0 | (string & {})> | undefined;
    "font-stretch"?: import("csstype").Property.FontStretch | undefined;
    "font-style"?: import("csstype").Property.FontStyle | undefined;
    "font-synthesis"?: import("csstype").Property.FontSynthesis | undefined;
    "font-variant"?: import("csstype").Property.FontVariant | undefined;
    "font-variant-alternates"?: import("csstype").Property.FontVariantAlternates | undefined;
    "font-variant-caps"?: import("csstype").Property.FontVariantCaps | undefined;
    "font-variant-east-asian"?: import("csstype").Property.FontVariantEastAsian | undefined;
    "font-variant-ligatures"?: import("csstype").Property.FontVariantLigatures | undefined;
    "font-variant-numeric"?: import("csstype").Property.FontVariantNumeric | undefined;
    "font-variant-position"?: import("csstype").Property.FontVariantPosition | undefined;
    "font-variation-settings"?: import("csstype").Property.FontVariationSettings | undefined;
    "font-weight"?: import("csstype").Property.FontWeight | undefined;
    "forced-color-adjust"?: import("csstype").Property.ForcedColorAdjust | undefined;
    "grid-auto-columns"?: import("csstype").Property.GridAutoColumns<0 | (string & {})> | undefined;
    "grid-auto-flow"?: import("csstype").Property.GridAutoFlow | undefined;
    "grid-auto-rows"?: import("csstype").Property.GridAutoRows<0 | (string & {})> | undefined;
    "grid-column-end"?: import("csstype").Property.GridColumnEnd | undefined;
    "grid-column-start"?: import("csstype").Property.GridColumnStart | undefined;
    "grid-row-end"?: import("csstype").Property.GridRowEnd | undefined;
    "grid-row-start"?: import("csstype").Property.GridRowStart | undefined;
    "grid-template-areas"?: import("csstype").Property.GridTemplateAreas | undefined;
    "grid-template-columns"?: import("csstype").Property.GridTemplateColumns<0 | (string & {})> | undefined;
    "grid-template-rows"?: import("csstype").Property.GridTemplateRows<0 | (string & {})> | undefined;
    "hanging-punctuation"?: import("csstype").Property.HangingPunctuation | undefined;
    height?: import("csstype").Property.Height<0 | (string & {})> | undefined;
    "hyphenate-character"?: import("csstype").Property.HyphenateCharacter | undefined;
    hyphens?: import("csstype").Property.Hyphens | undefined;
    "image-orientation"?: import("csstype").Property.ImageOrientation | undefined;
    "image-rendering"?: import("csstype").Property.ImageRendering | undefined;
    "image-resolution"?: import("csstype").Property.ImageResolution | undefined;
    "initial-letter"?: import("csstype").Property.InitialLetter | undefined;
    "inline-size"?: import("csstype").Property.InlineSize<0 | (string & {})> | undefined;
    "input-security"?: import("csstype").Property.InputSecurity | undefined;
    inset?: import("csstype").Property.Inset<0 | (string & {})> | undefined;
    "inset-block"?: import("csstype").Property.InsetBlock<0 | (string & {})> | undefined;
    "inset-block-end"?: import("csstype").Property.InsetBlockEnd<0 | (string & {})> | undefined;
    "inset-block-start"?: import("csstype").Property.InsetBlockStart<0 | (string & {})> | undefined;
    "inset-inline"?: import("csstype").Property.InsetInline<0 | (string & {})> | undefined;
    "inset-inline-end"?: import("csstype").Property.InsetInlineEnd<0 | (string & {})> | undefined;
    "inset-inline-start"?: import("csstype").Property.InsetInlineStart<0 | (string & {})> | undefined;
    isolation?: import("csstype").Property.Isolation | undefined;
    "justify-content"?: import("csstype").Property.JustifyContent | undefined;
    "justify-items"?: import("csstype").Property.JustifyItems | undefined;
    "justify-self"?: import("csstype").Property.JustifySelf | undefined;
    "justify-tracks"?: import("csstype").Property.JustifyTracks | undefined;
    left?: import("csstype").Property.Left<0 | (string & {})> | undefined;
    "letter-spacing"?: import("csstype").Property.LetterSpacing<0 | (string & {})> | undefined;
    "line-break"?: import("csstype").Property.LineBreak | undefined;
    "line-height"?: import("csstype").Property.LineHeight<0 | (string & {})> | undefined;
    "line-height-step"?: import("csstype").Property.LineHeightStep<0 | (string & {})> | undefined;
    "list-style-image"?: import("csstype").Property.ListStyleImage | undefined;
    "list-style-position"?: import("csstype").Property.ListStylePosition | undefined;
    "list-style-type"?: import("csstype").Property.ListStyleType | undefined;
    "margin-block"?: import("csstype").Property.MarginBlock<0 | (string & {})> | undefined;
    "margin-block-end"?: import("csstype").Property.MarginBlockEnd<0 | (string & {})> | undefined;
    "margin-block-start"?: import("csstype").Property.MarginBlockStart<0 | (string & {})> | undefined;
    "margin-bottom"?: import("csstype").Property.MarginBottom<0 | (string & {})> | undefined;
    "margin-inline"?: import("csstype").Property.MarginInline<0 | (string & {})> | undefined;
    "margin-inline-end"?: import("csstype").Property.MarginInlineEnd<0 | (string & {})> | undefined;
    "margin-inline-start"?: import("csstype").Property.MarginInlineStart<0 | (string & {})> | undefined;
    "margin-left"?: import("csstype").Property.MarginLeft<0 | (string & {})> | undefined;
    "margin-right"?: import("csstype").Property.MarginRight<0 | (string & {})> | undefined;
    "margin-top"?: import("csstype").Property.MarginTop<0 | (string & {})> | undefined;
    "mask-border-mode"?: import("csstype").Property.MaskBorderMode | undefined;
    "mask-border-outset"?: import("csstype").Property.MaskBorderOutset<0 | (string & {})> | undefined;
    "mask-border-repeat"?: import("csstype").Property.MaskBorderRepeat | undefined;
    "mask-border-slice"?: import("csstype").Property.MaskBorderSlice | undefined;
    "mask-border-source"?: import("csstype").Property.MaskBorderSource | undefined;
    "mask-border-width"?: import("csstype").Property.MaskBorderWidth<0 | (string & {})> | undefined;
    "mask-clip"?: import("csstype").Property.MaskClip | undefined;
    "mask-composite"?: import("csstype").Property.MaskComposite | undefined;
    "mask-image"?: import("csstype").Property.MaskImage | undefined;
    "mask-mode"?: import("csstype").Property.MaskMode | undefined;
    "mask-origin"?: import("csstype").Property.MaskOrigin | undefined;
    "mask-position"?: import("csstype").Property.MaskPosition<0 | (string & {})> | undefined;
    "mask-repeat"?: import("csstype").Property.MaskRepeat | undefined;
    "mask-size"?: import("csstype").Property.MaskSize<0 | (string & {})> | undefined;
    "mask-type"?: import("csstype").Property.MaskType | undefined;
    "math-depth"?: import("csstype").Property.MathDepth | undefined;
    "math-shift"?: import("csstype").Property.MathShift | undefined;
    "math-style"?: import("csstype").Property.MathStyle | undefined;
    "max-block-size"?: import("csstype").Property.MaxBlockSize<0 | (string & {})> | undefined;
    "max-height"?: import("csstype").Property.MaxHeight<0 | (string & {})> | undefined;
    "max-inline-size"?: import("csstype").Property.MaxInlineSize<0 | (string & {})> | undefined;
    "max-lines"?: import("csstype").Property.MaxLines | undefined;
    "max-width"?: import("csstype").Property.MaxWidth<0 | (string & {})> | undefined;
    "min-block-size"?: import("csstype").Property.MinBlockSize<0 | (string & {})> | undefined;
    "min-height"?: import("csstype").Property.MinHeight<0 | (string & {})> | undefined;
    "min-inline-size"?: import("csstype").Property.MinInlineSize<0 | (string & {})> | undefined;
    "min-width"?: import("csstype").Property.MinWidth<0 | (string & {})> | undefined;
    "mix-blend-mode"?: import("csstype").Property.MixBlendMode | undefined;
    "motion-distance"?: import("csstype").Property.OffsetDistance<0 | (string & {})> | undefined;
    "motion-path"?: import("csstype").Property.OffsetPath | undefined;
    "motion-rotation"?: import("csstype").Property.OffsetRotate | undefined;
    "object-fit"?: import("csstype").Property.ObjectFit | undefined;
    "object-position"?: import("csstype").Property.ObjectPosition<0 | (string & {})> | undefined;
    "offset-anchor"?: import("csstype").Property.OffsetAnchor<0 | (string & {})> | undefined;
    "offset-distance"?: import("csstype").Property.OffsetDistance<0 | (string & {})> | undefined;
    "offset-path"?: import("csstype").Property.OffsetPath | undefined;
    "offset-rotate"?: import("csstype").Property.OffsetRotate | undefined;
    "offset-rotation"?: import("csstype").Property.OffsetRotate | undefined;
    opacity?: import("csstype").Property.Opacity | undefined;
    order?: import("csstype").Property.Order | undefined;
    orphans?: import("csstype").Property.Orphans | undefined;
    "outline-color"?: import("csstype").Property.OutlineColor | undefined;
    "outline-offset"?: import("csstype").Property.OutlineOffset<0 | (string & {})> | undefined;
    "outline-style"?: import("csstype").Property.OutlineStyle | undefined;
    "outline-width"?: import("csstype").Property.OutlineWidth<0 | (string & {})> | undefined;
    "overflow-anchor"?: import("csstype").Property.OverflowAnchor | undefined;
    "overflow-block"?: import("csstype").Property.OverflowBlock | undefined;
    "overflow-clip-box"?: import("csstype").Property.OverflowClipBox | undefined;
    "overflow-clip-margin"?: import("csstype").Property.OverflowClipMargin<0 | (string & {})> | undefined;
    "overflow-inline"?: import("csstype").Property.OverflowInline | undefined;
    "overflow-wrap"?: import("csstype").Property.OverflowWrap | undefined;
    "overflow-x"?: import("csstype").Property.OverflowX | undefined;
    "overflow-y"?: import("csstype").Property.OverflowY | undefined;
    "overscroll-behavior-block"?: import("csstype").Property.OverscrollBehaviorBlock | undefined;
    "overscroll-behavior-inline"?: import("csstype").Property.OverscrollBehaviorInline | undefined;
    "overscroll-behavior-x"?: import("csstype").Property.OverscrollBehaviorX | undefined;
    "overscroll-behavior-y"?: import("csstype").Property.OverscrollBehaviorY | undefined;
    "padding-block"?: import("csstype").Property.PaddingBlock<0 | (string & {})> | undefined;
    "padding-block-end"?: import("csstype").Property.PaddingBlockEnd<0 | (string & {})> | undefined;
    "padding-block-start"?: import("csstype").Property.PaddingBlockStart<0 | (string & {})> | undefined;
    "padding-bottom"?: import("csstype").Property.PaddingBottom<0 | (string & {})> | undefined;
    "padding-inline"?: import("csstype").Property.PaddingInline<0 | (string & {})> | undefined;
    "padding-inline-end"?: import("csstype").Property.PaddingInlineEnd<0 | (string & {})> | undefined;
    "padding-inline-start"?: import("csstype").Property.PaddingInlineStart<0 | (string & {})> | undefined;
    "padding-left"?: import("csstype").Property.PaddingLeft<0 | (string & {})> | undefined;
    "padding-right"?: import("csstype").Property.PaddingRight<0 | (string & {})> | undefined;
    "padding-top"?: import("csstype").Property.PaddingTop<0 | (string & {})> | undefined;
    "page-break-after"?: import("csstype").Property.PageBreakAfter | undefined;
    "page-break-before"?: import("csstype").Property.PageBreakBefore | undefined;
    "page-break-inside"?: import("csstype").Property.PageBreakInside | undefined;
    "paint-order"?: import("csstype").Property.PaintOrder | undefined;
    perspective?: import("csstype").Property.Perspective<0 | (string & {})> | undefined;
    "perspective-origin"?: import("csstype").Property.PerspectiveOrigin<0 | (string & {})> | undefined;
    "place-content"?: import("csstype").Property.PlaceContent | undefined;
    "pointer-events"?: import("csstype").Property.PointerEvents | undefined;
    position?: import("csstype").Property.Position | undefined;
    "print-color-adjust"?: import("csstype").Property.PrintColorAdjust | undefined;
    quotes?: import("csstype").Property.Quotes | undefined;
    resize?: import("csstype").Property.Resize | undefined;
    right?: import("csstype").Property.Right<0 | (string & {})> | undefined;
    rotate?: import("csstype").Property.Rotate | undefined;
    "row-gap"?: import("csstype").Property.RowGap<0 | (string & {})> | undefined;
    "ruby-align"?: import("csstype").Property.RubyAlign | undefined;
    "ruby-merge"?: import("csstype").Property.RubyMerge | undefined;
    "ruby-position"?: import("csstype").Property.RubyPosition | undefined;
    scale?: import("csstype").Property.Scale | undefined;
    "scroll-behavior"?: import("csstype").Property.ScrollBehavior | undefined;
    "scroll-margin"?: import("csstype").Property.ScrollMargin<0 | (string & {})> | undefined;
    "scroll-margin-block"?: import("csstype").Property.ScrollMarginBlock<0 | (string & {})> | undefined;
    "scroll-margin-block-end"?: import("csstype").Property.ScrollMarginBlockEnd<0 | (string & {})> | undefined;
    "scroll-margin-block-start"?: import("csstype").Property.ScrollMarginBlockStart<0 | (string & {})> | undefined;
    "scroll-margin-bottom"?: import("csstype").Property.ScrollMarginBottom<0 | (string & {})> | undefined;
    "scroll-margin-inline"?: import("csstype").Property.ScrollMarginInline<0 | (string & {})> | undefined;
    "scroll-margin-inline-end"?: import("csstype").Property.ScrollMarginInlineEnd<0 | (string & {})> | undefined;
    "scroll-margin-inline-start"?: import("csstype").Property.ScrollMarginInlineStart<0 | (string & {})> | undefined;
    "scroll-margin-left"?: import("csstype").Property.ScrollMarginLeft<0 | (string & {})> | undefined;
    "scroll-margin-right"?: import("csstype").Property.ScrollMarginRight<0 | (string & {})> | undefined;
    "scroll-margin-top"?: import("csstype").Property.ScrollMarginTop<0 | (string & {})> | undefined;
    "scroll-padding"?: import("csstype").Property.ScrollPadding<0 | (string & {})> | undefined;
    "scroll-padding-block"?: import("csstype").Property.ScrollPaddingBlock<0 | (string & {})> | undefined;
    "scroll-padding-block-end"?: import("csstype").Property.ScrollPaddingBlockEnd<0 | (string & {})> | undefined;
    "scroll-padding-block-start"?: import("csstype").Property.ScrollPaddingBlockStart<0 | (string & {})> | undefined;
    "scroll-padding-bottom"?: import("csstype").Property.ScrollPaddingBottom<0 | (string & {})> | undefined;
    "scroll-padding-inline"?: import("csstype").Property.ScrollPaddingInline<0 | (string & {})> | undefined;
    "scroll-padding-inline-end"?: import("csstype").Property.ScrollPaddingInlineEnd<0 | (string & {})> | undefined;
    "scroll-padding-inline-start"?: import("csstype").Property.ScrollPaddingInlineStart<0 | (string & {})> | undefined;
    "scroll-padding-left"?: import("csstype").Property.ScrollPaddingLeft<0 | (string & {})> | undefined;
    "scroll-padding-right"?: import("csstype").Property.ScrollPaddingRight<0 | (string & {})> | undefined;
    "scroll-padding-top"?: import("csstype").Property.ScrollPaddingTop<0 | (string & {})> | undefined;
    "scroll-snap-align"?: import("csstype").Property.ScrollSnapAlign | undefined;
    "scroll-snap-margin"?: import("csstype").Property.ScrollMargin<0 | (string & {})> | undefined;
    "scroll-snap-margin-bottom"?: import("csstype").Property.ScrollMarginBottom<0 | (string & {})> | undefined;
    "scroll-snap-margin-left"?: import("csstype").Property.ScrollMarginLeft<0 | (string & {})> | undefined;
    "scroll-snap-margin-right"?: import("csstype").Property.ScrollMarginRight<0 | (string & {})> | undefined;
    "scroll-snap-margin-top"?: import("csstype").Property.ScrollMarginTop<0 | (string & {})> | undefined;
    "scroll-snap-stop"?: import("csstype").Property.ScrollSnapStop | undefined;
    "scroll-snap-type"?: import("csstype").Property.ScrollSnapType | undefined;
    "scrollbar-color"?: import("csstype").Property.ScrollbarColor | undefined;
    "scrollbar-gutter"?: import("csstype").Property.ScrollbarGutter | undefined;
    "scrollbar-width"?: import("csstype").Property.ScrollbarWidth | undefined;
    "shape-image-threshold"?: import("csstype").Property.ShapeImageThreshold | undefined;
    "shape-margin"?: import("csstype").Property.ShapeMargin<0 | (string & {})> | undefined;
    "shape-outside"?: import("csstype").Property.ShapeOutside | undefined;
    "tab-size"?: import("csstype").Property.TabSize<0 | (string & {})> | undefined;
    "table-layout"?: import("csstype").Property.TableLayout | undefined;
    "text-align"?: import("csstype").Property.TextAlign | undefined;
    "text-align-last"?: import("csstype").Property.TextAlignLast | undefined;
    "text-combine-upright"?: import("csstype").Property.TextCombineUpright | undefined;
    "text-decoration-color"?: import("csstype").Property.TextDecorationColor | undefined;
    "text-decoration-line"?: import("csstype").Property.TextDecorationLine | undefined;
    "text-decoration-skip"?: import("csstype").Property.TextDecorationSkip | undefined;
    "text-decoration-skip-ink"?: import("csstype").Property.TextDecorationSkipInk | undefined;
    "text-decoration-style"?: import("csstype").Property.TextDecorationStyle | undefined;
    "text-decoration-thickness"?: import("csstype").Property.TextDecorationThickness<0 | (string & {})> | undefined;
    "text-emphasis-color"?: import("csstype").Property.TextEmphasisColor | undefined;
    "text-emphasis-position"?: import("csstype").Property.TextEmphasisPosition | undefined;
    "text-emphasis-style"?: import("csstype").Property.TextEmphasisStyle | undefined;
    "text-indent"?: import("csstype").Property.TextIndent<0 | (string & {})> | undefined;
    "text-justify"?: import("csstype").Property.TextJustify | undefined;
    "text-orientation"?: import("csstype").Property.TextOrientation | undefined;
    "text-overflow"?: import("csstype").Property.TextOverflow | undefined;
    "text-rendering"?: import("csstype").Property.TextRendering | undefined;
    "text-shadow"?: import("csstype").Property.TextShadow | undefined;
    "text-size-adjust"?: import("csstype").Property.TextSizeAdjust | undefined;
    "text-transform"?: import("csstype").Property.TextTransform | undefined;
    "text-underline-offset"?: import("csstype").Property.TextUnderlineOffset<0 | (string & {})> | undefined;
    "text-underline-position"?: import("csstype").Property.TextUnderlinePosition | undefined;
    top?: import("csstype").Property.Top<0 | (string & {})> | undefined;
    "touch-action"?: import("csstype").Property.TouchAction | undefined;
    transform?: import("csstype").Property.Transform | undefined;
    "transform-box"?: import("csstype").Property.TransformBox | undefined;
    "transform-origin"?: import("csstype").Property.TransformOrigin<0 | (string & {})> | undefined;
    "transform-style"?: import("csstype").Property.TransformStyle | undefined;
    "transition-delay"?: import("csstype").Property.TransitionDelay<string & {}> | undefined;
    "transition-duration"?: import("csstype").Property.TransitionDuration<string & {}> | undefined;
    "transition-property"?: import("csstype").Property.TransitionProperty | undefined;
    "transition-timing-function"?: import("csstype").Property.TransitionTimingFunction | undefined;
    translate?: import("csstype").Property.Translate<0 | (string & {})> | undefined;
    "unicode-bidi"?: import("csstype").Property.UnicodeBidi | undefined;
    "user-select"?: import("csstype").Property.UserSelect | undefined;
    "vertical-align"?: import("csstype").Property.VerticalAlign<0 | (string & {})> | undefined;
    visibility?: import("csstype").Property.Visibility | undefined;
    "white-space"?: import("csstype").Property.WhiteSpace | undefined;
    widows?: import("csstype").Property.Widows | undefined;
    width?: import("csstype").Property.Width<0 | (string & {})> | undefined;
    "will-change"?: import("csstype").Property.WillChange | undefined;
    "word-break"?: import("csstype").Property.WordBreak | undefined;
    "word-spacing"?: import("csstype").Property.WordSpacing<0 | (string & {})> | undefined;
    "word-wrap"?: import("csstype").Property.WordWrap | undefined;
    "writing-mode"?: import("csstype").Property.WritingMode | undefined;
    "z-index"?: import("csstype").Property.ZIndex | undefined;
    zoom?: import("csstype").Property.Zoom | undefined;
    all?: import("csstype").Globals | undefined;
    animation?: import("csstype").Property.Animation<string & {}> | undefined;
    background?: import("csstype").Property.Background<0 | (string & {})> | undefined;
    "background-position"?: import("csstype").Property.BackgroundPosition<0 | (string & {})> | undefined;
    border?: import("csstype").Property.Border<0 | (string & {})> | undefined;
    "border-block"?: import("csstype").Property.BorderBlock<0 | (string & {})> | undefined;
    "border-block-end"?: import("csstype").Property.BorderBlockEnd<0 | (string & {})> | undefined;
    "border-block-start"?: import("csstype").Property.BorderBlockStart<0 | (string & {})> | undefined;
    "border-bottom"?: import("csstype").Property.BorderBottom<0 | (string & {})> | undefined;
    "border-color"?: import("csstype").Property.BorderColor | undefined;
    "border-image"?: import("csstype").Property.BorderImage | undefined;
    "border-inline"?: import("csstype").Property.BorderInline<0 | (string & {})> | undefined;
    "border-inline-end"?: import("csstype").Property.BorderInlineEnd<0 | (string & {})> | undefined;
    "border-inline-start"?: import("csstype").Property.BorderInlineStart<0 | (string & {})> | undefined;
    "border-left"?: import("csstype").Property.BorderLeft<0 | (string & {})> | undefined;
    "border-radius"?: import("csstype").Property.BorderRadius<0 | (string & {})> | undefined;
    "border-right"?: import("csstype").Property.BorderRight<0 | (string & {})> | undefined;
    "border-style"?: import("csstype").Property.BorderStyle | undefined;
    "border-top"?: import("csstype").Property.BorderTop<0 | (string & {})> | undefined;
    "border-width"?: import("csstype").Property.BorderWidth<0 | (string & {})> | undefined;
    "column-rule"?: import("csstype").Property.ColumnRule<0 | (string & {})> | undefined;
    columns?: import("csstype").Property.Columns<0 | (string & {})> | undefined;
    flex?: import("csstype").Property.Flex<0 | (string & {})> | undefined;
    "flex-flow"?: import("csstype").Property.FlexFlow | undefined;
    font?: import("csstype").Property.Font | undefined;
    gap?: import("csstype").Property.Gap<0 | (string & {})> | undefined;
    grid?: import("csstype").Property.Grid | undefined;
    "grid-area"?: import("csstype").Property.GridArea | undefined;
    "grid-column"?: import("csstype").Property.GridColumn | undefined;
    "grid-row"?: import("csstype").Property.GridRow | undefined;
    "grid-template"?: import("csstype").Property.GridTemplate | undefined;
    "line-clamp"?: import("csstype").Property.LineClamp | undefined;
    "list-style"?: import("csstype").Property.ListStyle | undefined;
    margin?: import("csstype").Property.Margin<0 | (string & {})> | undefined;
    mask?: import("csstype").Property.Mask<0 | (string & {})> | undefined;
    "mask-border"?: import("csstype").Property.MaskBorder | undefined;
    motion?: import("csstype").Property.Offset<0 | (string & {})> | undefined;
    offset?: import("csstype").Property.Offset<0 | (string & {})> | undefined;
    outline?: import("csstype").Property.Outline<0 | (string & {})> | undefined;
    overflow?: import("csstype").Property.Overflow | undefined;
    "overscroll-behavior"?: import("csstype").Property.OverscrollBehavior | undefined;
    padding?: import("csstype").Property.Padding<0 | (string & {})> | undefined;
    "place-items"?: import("csstype").Property.PlaceItems | undefined;
    "place-self"?: import("csstype").Property.PlaceSelf | undefined;
    "text-decoration"?: import("csstype").Property.TextDecoration<0 | (string & {})> | undefined;
    "text-emphasis"?: import("csstype").Property.TextEmphasis | undefined;
    transition?: import("csstype").Property.Transition<string & {}> | undefined;
    "-moz-animation-delay"?: import("csstype").Property.AnimationDelay<string & {}> | undefined;
    "-moz-animation-direction"?: import("csstype").Property.AnimationDirection | undefined;
    "-moz-animation-duration"?: import("csstype").Property.AnimationDuration<string & {}> | undefined;
    "-moz-animation-fill-mode"?: import("csstype").Property.AnimationFillMode | undefined;
    "-moz-animation-iteration-count"?: import("csstype").Property.AnimationIterationCount | undefined;
    "-moz-animation-name"?: import("csstype").Property.AnimationName | undefined;
    "-moz-animation-play-state"?: import("csstype").Property.AnimationPlayState | undefined;
    "-moz-animation-timing-function"?: import("csstype").Property.AnimationTimingFunction | undefined;
    "-moz-appearance"?: import("csstype").Property.MozAppearance | undefined;
    "-moz-backface-visibility"?: import("csstype").Property.BackfaceVisibility | undefined;
    "-moz-border-bottom-colors"?: import("csstype").Property.MozBorderBottomColors | undefined;
    "-moz-border-end-color"?: import("csstype").Property.BorderInlineEndColor | undefined;
    "-moz-border-end-style"?: import("csstype").Property.BorderInlineEndStyle | undefined;
    "-moz-border-end-width"?: import("csstype").Property.BorderInlineEndWidth<0 | (string & {})> | undefined;
    "-moz-border-left-colors"?: import("csstype").Property.MozBorderLeftColors | undefined;
    "-moz-border-right-colors"?: import("csstype").Property.MozBorderRightColors | undefined;
    "-moz-border-start-color"?: import("csstype").Property.BorderInlineStartColor | undefined;
    "-moz-border-start-style"?: import("csstype").Property.BorderInlineStartStyle | undefined;
    "-moz-border-top-colors"?: import("csstype").Property.MozBorderTopColors | undefined;
    "-moz-box-sizing"?: import("csstype").Property.BoxSizing | undefined;
    "-moz-column-count"?: import("csstype").Property.ColumnCount | undefined;
    "-moz-column-fill"?: import("csstype").Property.ColumnFill | undefined;
    "-moz-column-rule-color"?: import("csstype").Property.ColumnRuleColor | undefined;
    "-moz-column-rule-style"?: import("csstype").Property.ColumnRuleStyle | undefined;
    "-moz-column-rule-width"?: import("csstype").Property.ColumnRuleWidth<0 | (string & {})> | undefined;
    "-moz-column-width"?: import("csstype").Property.ColumnWidth<0 | (string & {})> | undefined;
    "-moz-context-properties"?: import("csstype").Property.MozContextProperties | undefined;
    "-moz-font-feature-settings"?: import("csstype").Property.FontFeatureSettings | undefined;
    "-moz-font-language-override"?: import("csstype").Property.FontLanguageOverride | undefined;
    "-moz-hyphens"?: import("csstype").Property.Hyphens | undefined;
    "-moz-image-region"?: import("csstype").Property.MozImageRegion | undefined;
    "-moz-margin-end"?: import("csstype").Property.MarginInlineEnd<0 | (string & {})> | undefined;
    "-moz-margin-start"?: import("csstype").Property.MarginInlineStart<0 | (string & {})> | undefined;
    "-moz-orient"?: import("csstype").Property.MozOrient | undefined;
    "-moz-osx-font-smoothing"?: import("csstype").Property.FontSmooth<0 | (string & {})> | undefined;
    "-moz-padding-end"?: import("csstype").Property.PaddingInlineEnd<0 | (string & {})> | undefined;
    "-moz-padding-start"?: import("csstype").Property.PaddingInlineStart<0 | (string & {})> | undefined;
    "-moz-perspective"?: import("csstype").Property.Perspective<0 | (string & {})> | undefined;
    "-moz-perspective-origin"?: import("csstype").Property.PerspectiveOrigin<0 | (string & {})> | undefined;
    "-moz-stack-sizing"?: import("csstype").Property.MozStackSizing | undefined;
    "-moz-tab-size"?: import("csstype").Property.TabSize<0 | (string & {})> | undefined;
    "-moz-text-blink"?: import("csstype").Property.MozTextBlink | undefined;
    "-moz-text-size-adjust"?: import("csstype").Property.TextSizeAdjust | undefined;
    "-moz-transform-origin"?: import("csstype").Property.TransformOrigin<0 | (string & {})> | undefined;
    "-moz-transform-style"?: import("csstype").Property.TransformStyle | undefined;
    "-moz-transition-delay"?: import("csstype").Property.TransitionDelay<string & {}> | undefined;
    "-moz-transition-duration"?: import("csstype").Property.TransitionDuration<string & {}> | undefined;
    "-moz-transition-property"?: import("csstype").Property.TransitionProperty | undefined;
    "-moz-transition-timing-function"?: import("csstype").Property.TransitionTimingFunction | undefined;
    "-moz-user-focus"?: import("csstype").Property.MozUserFocus | undefined;
    "-moz-user-modify"?: import("csstype").Property.MozUserModify | undefined;
    "-moz-user-select"?: import("csstype").Property.UserSelect | undefined;
    "-moz-window-dragging"?: import("csstype").Property.MozWindowDragging | undefined;
    "-moz-window-shadow"?: import("csstype").Property.MozWindowShadow | undefined;
    "-ms-accelerator"?: import("csstype").Property.MsAccelerator | undefined;
    "-ms-block-progression"?: import("csstype").Property.MsBlockProgression | undefined;
    "-ms-content-zoom-chaining"?: import("csstype").Property.MsContentZoomChaining | undefined;
    "-ms-content-zoom-limit-max"?: import("csstype").Property.MsContentZoomLimitMax | undefined;
    "-ms-content-zoom-limit-min"?: import("csstype").Property.MsContentZoomLimitMin | undefined;
    "-ms-content-zoom-snap-points"?: import("csstype").Property.MsContentZoomSnapPoints | undefined;
    "-ms-content-zoom-snap-type"?: import("csstype").Property.MsContentZoomSnapType | undefined;
    "-ms-content-zooming"?: import("csstype").Property.MsContentZooming | undefined;
    "-ms-filter"?: import("csstype").Property.MsFilter | undefined;
    "-ms-flex-direction"?: import("csstype").Property.FlexDirection | undefined;
    "-ms-flex-positive"?: import("csstype").Property.FlexGrow | undefined;
    "-ms-flow-from"?: import("csstype").Property.MsFlowFrom | undefined;
    "-ms-flow-into"?: import("csstype").Property.MsFlowInto | undefined;
    "-ms-grid-columns"?: import("csstype").Property.MsGridColumns<0 | (string & {})> | undefined;
    "-ms-grid-rows"?: import("csstype").Property.MsGridRows<0 | (string & {})> | undefined;
    "-ms-high-contrast-adjust"?: import("csstype").Property.MsHighContrastAdjust | undefined;
    "-ms-hyphenate-limit-chars"?: import("csstype").Property.MsHyphenateLimitChars | undefined;
    "-ms-hyphenate-limit-lines"?: import("csstype").Property.MsHyphenateLimitLines | undefined;
    "-ms-hyphenate-limit-zone"?: import("csstype").Property.MsHyphenateLimitZone<0 | (string & {})> | undefined;
    "-ms-hyphens"?: import("csstype").Property.Hyphens | undefined;
    "-ms-ime-align"?: import("csstype").Property.MsImeAlign | undefined;
    "-ms-line-break"?: import("csstype").Property.LineBreak | undefined;
    "-ms-order"?: import("csstype").Property.Order | undefined;
    "-ms-overflow-style"?: import("csstype").Property.MsOverflowStyle | undefined;
    "-ms-overflow-x"?: import("csstype").Property.OverflowX | undefined;
    "-ms-overflow-y"?: import("csstype").Property.OverflowY | undefined;
    "-ms-scroll-chaining"?: import("csstype").Property.MsScrollChaining | undefined;
    "-ms-scroll-limit-x-max"?: import("csstype").Property.MsScrollLimitXMax<0 | (string & {})> | undefined;
    "-ms-scroll-limit-x-min"?: import("csstype").Property.MsScrollLimitXMin<0 | (string & {})> | undefined;
    "-ms-scroll-limit-y-max"?: import("csstype").Property.MsScrollLimitYMax<0 | (string & {})> | undefined;
    "-ms-scroll-limit-y-min"?: import("csstype").Property.MsScrollLimitYMin<0 | (string & {})> | undefined;
    "-ms-scroll-rails"?: import("csstype").Property.MsScrollRails | undefined;
    "-ms-scroll-snap-points-x"?: import("csstype").Property.MsScrollSnapPointsX | undefined;
    "-ms-scroll-snap-points-y"?: import("csstype").Property.MsScrollSnapPointsY | undefined;
    "-ms-scroll-snap-type"?: import("csstype").Property.MsScrollSnapType | undefined;
    "-ms-scroll-translation"?: import("csstype").Property.MsScrollTranslation | undefined;
    "-ms-scrollbar-3dlight-color"?: import("csstype").Property.MsScrollbar3dlightColor | undefined;
    "-ms-scrollbar-arrow-color"?: import("csstype").Property.MsScrollbarArrowColor | undefined;
    "-ms-scrollbar-base-color"?: import("csstype").Property.MsScrollbarBaseColor | undefined;
    "-ms-scrollbar-darkshadow-color"?: import("csstype").Property.MsScrollbarDarkshadowColor | undefined;
    "-ms-scrollbar-face-color"?: import("csstype").Property.MsScrollbarFaceColor | undefined;
    "-ms-scrollbar-highlight-color"?: import("csstype").Property.MsScrollbarHighlightColor | undefined;
    "-ms-scrollbar-shadow-color"?: import("csstype").Property.MsScrollbarShadowColor | undefined;
    "-ms-scrollbar-track-color"?: import("csstype").Property.MsScrollbarTrackColor | undefined;
    "-ms-text-autospace"?: import("csstype").Property.MsTextAutospace | undefined;
    "-ms-text-combine-horizontal"?: import("csstype").Property.TextCombineUpright | undefined;
    "-ms-text-overflow"?: import("csstype").Property.TextOverflow | undefined;
    "-ms-touch-action"?: import("csstype").Property.TouchAction | undefined;
    "-ms-touch-select"?: import("csstype").Property.MsTouchSelect | undefined;
    "-ms-transform"?: import("csstype").Property.Transform | undefined;
    "-ms-transform-origin"?: import("csstype").Property.TransformOrigin<0 | (string & {})> | undefined;
    "-ms-transition-delay"?: import("csstype").Property.TransitionDelay<string & {}> | undefined;
    "-ms-transition-duration"?: import("csstype").Property.TransitionDuration<string & {}> | undefined;
    "-ms-transition-property"?: import("csstype").Property.TransitionProperty | undefined;
    "-ms-transition-timing-function"?: import("csstype").Property.TransitionTimingFunction | undefined;
    "-ms-user-select"?: import("csstype").Property.MsUserSelect | undefined;
    "-ms-word-break"?: import("csstype").Property.WordBreak | undefined;
    "-ms-wrap-flow"?: import("csstype").Property.MsWrapFlow | undefined;
    "-ms-wrap-margin"?: import("csstype").Property.MsWrapMargin<0 | (string & {})> | undefined;
    "-ms-wrap-through"?: import("csstype").Property.MsWrapThrough | undefined;
    "-ms-writing-mode"?: import("csstype").Property.WritingMode | undefined;
    "-webkit-align-content"?: import("csstype").Property.AlignContent | undefined;
    "-webkit-align-items"?: import("csstype").Property.AlignItems | undefined;
    "-webkit-align-self"?: import("csstype").Property.AlignSelf | undefined;
    "-webkit-animation-delay"?: import("csstype").Property.AnimationDelay<string & {}> | undefined;
    "-webkit-animation-direction"?: import("csstype").Property.AnimationDirection | undefined;
    "-webkit-animation-duration"?: import("csstype").Property.AnimationDuration<string & {}> | undefined;
    "-webkit-animation-fill-mode"?: import("csstype").Property.AnimationFillMode | undefined;
    "-webkit-animation-iteration-count"?: import("csstype").Property.AnimationIterationCount | undefined;
    "-webkit-animation-name"?: import("csstype").Property.AnimationName | undefined;
    "-webkit-animation-play-state"?: import("csstype").Property.AnimationPlayState | undefined;
    "-webkit-animation-timing-function"?: import("csstype").Property.AnimationTimingFunction | undefined;
    "-webkit-appearance"?: import("csstype").Property.WebkitAppearance | undefined;
    "-webkit-backdrop-filter"?: import("csstype").Property.BackdropFilter | undefined;
    "-webkit-backface-visibility"?: import("csstype").Property.BackfaceVisibility | undefined;
    "-webkit-background-clip"?: import("csstype").Property.BackgroundClip | undefined;
    "-webkit-background-origin"?: import("csstype").Property.BackgroundOrigin | undefined;
    "-webkit-background-size"?: import("csstype").Property.BackgroundSize<0 | (string & {})> | undefined;
    "-webkit-border-before-color"?: import("csstype").Property.WebkitBorderBeforeColor | undefined;
    "-webkit-border-before-style"?: import("csstype").Property.WebkitBorderBeforeStyle | undefined;
    "-webkit-border-before-width"?: import("csstype").Property.WebkitBorderBeforeWidth<0 | (string & {})> | undefined;
    "-webkit-border-bottom-left-radius"?: import("csstype").Property.BorderBottomLeftRadius<0 | (string & {})> | undefined;
    "-webkit-border-bottom-right-radius"?: import("csstype").Property.BorderBottomRightRadius<0 | (string & {})> | undefined;
    "-webkit-border-image-slice"?: import("csstype").Property.BorderImageSlice | undefined;
    "-webkit-border-top-left-radius"?: import("csstype").Property.BorderTopLeftRadius<0 | (string & {})> | undefined;
    "-webkit-border-top-right-radius"?: import("csstype").Property.BorderTopRightRadius<0 | (string & {})> | undefined;
    "-webkit-box-decoration-break"?: import("csstype").Property.BoxDecorationBreak | undefined;
    "-webkit-box-reflect"?: import("csstype").Property.WebkitBoxReflect<0 | (string & {})> | undefined;
    "-webkit-box-shadow"?: import("csstype").Property.BoxShadow | undefined;
    "-webkit-box-sizing"?: import("csstype").Property.BoxSizing | undefined;
    "-webkit-clip-path"?: import("csstype").Property.ClipPath | undefined;
    "-webkit-column-count"?: import("csstype").Property.ColumnCount | undefined;
    "-webkit-column-fill"?: import("csstype").Property.ColumnFill | undefined;
    "-webkit-column-rule-color"?: import("csstype").Property.ColumnRuleColor | undefined;
    "-webkit-column-rule-style"?: import("csstype").Property.ColumnRuleStyle | undefined;
    "-webkit-column-rule-width"?: import("csstype").Property.ColumnRuleWidth<0 | (string & {})> | undefined;
    "-webkit-column-span"?: import("csstype").Property.ColumnSpan | undefined;
    "-webkit-column-width"?: import("csstype").Property.ColumnWidth<0 | (string & {})> | undefined;
    "-webkit-filter"?: import("csstype").Property.Filter | undefined;
    "-webkit-flex-basis"?: import("csstype").Property.FlexBasis<0 | (string & {})> | undefined;
    "-webkit-flex-direction"?: import("csstype").Property.FlexDirection | undefined;
    "-webkit-flex-grow"?: import("csstype").Property.FlexGrow | undefined;
    "-webkit-flex-shrink"?: import("csstype").Property.FlexShrink | undefined;
    "-webkit-flex-wrap"?: import("csstype").Property.FlexWrap | undefined;
    "-webkit-font-feature-settings"?: import("csstype").Property.FontFeatureSettings | undefined;
    "-webkit-font-kerning"?: import("csstype").Property.FontKerning | undefined;
    "-webkit-font-smoothing"?: import("csstype").Property.FontSmooth<0 | (string & {})> | undefined;
    "-webkit-font-variant-ligatures"?: import("csstype").Property.FontVariantLigatures | undefined;
    "-webkit-hyphenate-character"?: import("csstype").Property.HyphenateCharacter | undefined;
    "-webkit-hyphens"?: import("csstype").Property.Hyphens | undefined;
    "-webkit-initial-letter"?: import("csstype").Property.InitialLetter | undefined;
    "-webkit-justify-content"?: import("csstype").Property.JustifyContent | undefined;
    "-webkit-line-break"?: import("csstype").Property.LineBreak | undefined;
    "-webkit-line-clamp"?: import("csstype").Property.WebkitLineClamp | undefined;
    "-webkit-margin-end"?: import("csstype").Property.MarginInlineEnd<0 | (string & {})> | undefined;
    "-webkit-margin-start"?: import("csstype").Property.MarginInlineStart<0 | (string & {})> | undefined;
    "-webkit-mask-attachment"?: import("csstype").Property.WebkitMaskAttachment | undefined;
    "-webkit-mask-box-image-outset"?: import("csstype").Property.MaskBorderOutset<0 | (string & {})> | undefined;
    "-webkit-mask-box-image-repeat"?: import("csstype").Property.MaskBorderRepeat | undefined;
    "-webkit-mask-box-image-slice"?: import("csstype").Property.MaskBorderSlice | undefined;
    "-webkit-mask-box-image-source"?: import("csstype").Property.MaskBorderSource | undefined;
    "-webkit-mask-box-image-width"?: import("csstype").Property.MaskBorderWidth<0 | (string & {})> | undefined;
    "-webkit-mask-clip"?: import("csstype").Property.WebkitMaskClip | undefined;
    "-webkit-mask-composite"?: import("csstype").Property.WebkitMaskComposite | undefined;
    "-webkit-mask-image"?: import("csstype").Property.WebkitMaskImage | undefined;
    "-webkit-mask-origin"?: import("csstype").Property.WebkitMaskOrigin | undefined;
    "-webkit-mask-position"?: import("csstype").Property.WebkitMaskPosition<0 | (string & {})> | undefined;
    "-webkit-mask-position-x"?: import("csstype").Property.WebkitMaskPositionX<0 | (string & {})> | undefined;
    "-webkit-mask-position-y"?: import("csstype").Property.WebkitMaskPositionY<0 | (string & {})> | undefined;
    "-webkit-mask-repeat"?: import("csstype").Property.WebkitMaskRepeat | undefined;
    "-webkit-mask-repeat-x"?: import("csstype").Property.WebkitMaskRepeatX | undefined;
    "-webkit-mask-repeat-y"?: import("csstype").Property.WebkitMaskRepeatY | undefined;
    "-webkit-mask-size"?: import("csstype").Property.WebkitMaskSize<0 | (string & {})> | undefined;
    "-webkit-max-inline-size"?: import("csstype").Property.MaxInlineSize<0 | (string & {})> | undefined;
    "-webkit-order"?: import("csstype").Property.Order | undefined;
    "-webkit-overflow-scrolling"?: import("csstype").Property.WebkitOverflowScrolling | undefined;
    "-webkit-padding-end"?: import("csstype").Property.PaddingInlineEnd<0 | (string & {})> | undefined;
    "-webkit-padding-start"?: import("csstype").Property.PaddingInlineStart<0 | (string & {})> | undefined;
    "-webkit-perspective"?: import("csstype").Property.Perspective<0 | (string & {})> | undefined;
    "-webkit-perspective-origin"?: import("csstype").Property.PerspectiveOrigin<0 | (string & {})> | undefined;
    "-webkit-print-color-adjust"?: import("csstype").Property.PrintColorAdjust | undefined;
    "-webkit-ruby-position"?: import("csstype").Property.RubyPosition | undefined;
    "-webkit-scroll-snap-type"?: import("csstype").Property.ScrollSnapType | undefined;
    "-webkit-shape-margin"?: import("csstype").Property.ShapeMargin<0 | (string & {})> | undefined;
    "-webkit-tap-highlight-color"?: import("csstype").Property.WebkitTapHighlightColor | undefined;
    "-webkit-text-combine"?: import("csstype").Property.TextCombineUpright | undefined;
    "-webkit-text-decoration-color"?: import("csstype").Property.TextDecorationColor | undefined;
    "-webkit-text-decoration-line"?: import("csstype").Property.TextDecorationLine | undefined;
    "-webkit-text-decoration-skip"?: import("csstype").Property.TextDecorationSkip | undefined;
    "-webkit-text-decoration-style"?: import("csstype").Property.TextDecorationStyle | undefined;
    "-webkit-text-emphasis-color"?: import("csstype").Property.TextEmphasisColor | undefined;
    "-webkit-text-emphasis-position"?: import("csstype").Property.TextEmphasisPosition | undefined;
    "-webkit-text-emphasis-style"?: import("csstype").Property.TextEmphasisStyle | undefined;
    "-webkit-text-fill-color"?: import("csstype").Property.WebkitTextFillColor | undefined;
    "-webkit-text-orientation"?: import("csstype").Property.TextOrientation | undefined;
    "-webkit-text-size-adjust"?: import("csstype").Property.TextSizeAdjust | undefined;
    "-webkit-text-stroke-color"?: import("csstype").Property.WebkitTextStrokeColor | undefined;
    "-webkit-text-stroke-width"?: import("csstype").Property.WebkitTextStrokeWidth<0 | (string & {})> | undefined;
    "-webkit-text-underline-position"?: import("csstype").Property.TextUnderlinePosition | undefined;
    "-webkit-touch-callout"?: import("csstype").Property.WebkitTouchCallout | undefined;
    "-webkit-transform"?: import("csstype").Property.Transform | undefined;
    "-webkit-transform-origin"?: import("csstype").Property.TransformOrigin<0 | (string & {})> | undefined;
    "-webkit-transform-style"?: import("csstype").Property.TransformStyle | undefined;
    "-webkit-transition-delay"?: import("csstype").Property.TransitionDelay<string & {}> | undefined;
    "-webkit-transition-duration"?: import("csstype").Property.TransitionDuration<string & {}> | undefined;
    "-webkit-transition-property"?: import("csstype").Property.TransitionProperty | undefined;
    "-webkit-transition-timing-function"?: import("csstype").Property.TransitionTimingFunction | undefined;
    "-webkit-user-modify"?: import("csstype").Property.WebkitUserModify | undefined;
    "-webkit-user-select"?: import("csstype").Property.UserSelect | undefined;
    "-webkit-writing-mode"?: import("csstype").Property.WritingMode | undefined;
    "-moz-animation"?: import("csstype").Property.Animation<string & {}> | undefined;
    "-moz-border-image"?: import("csstype").Property.BorderImage | undefined;
    "-moz-column-rule"?: import("csstype").Property.ColumnRule<0 | (string & {})> | undefined;
    "-moz-columns"?: import("csstype").Property.Columns<0 | (string & {})> | undefined;
    "-moz-transition"?: import("csstype").Property.Transition<string & {}> | undefined;
    "-ms-content-zoom-limit"?: import("csstype").Property.MsContentZoomLimit | undefined;
    "-ms-content-zoom-snap"?: import("csstype").Property.MsContentZoomSnap | undefined;
    "-ms-flex"?: import("csstype").Property.Flex<0 | (string & {})> | undefined;
    "-ms-scroll-limit"?: import("csstype").Property.MsScrollLimit | undefined;
    "-ms-scroll-snap-x"?: import("csstype").Property.MsScrollSnapX | undefined;
    "-ms-scroll-snap-y"?: import("csstype").Property.MsScrollSnapY | undefined;
    "-ms-transition"?: import("csstype").Property.Transition<string & {}> | undefined;
    "-webkit-animation"?: import("csstype").Property.Animation<string & {}> | undefined;
    "-webkit-border-before"?: import("csstype").Property.WebkitBorderBefore<0 | (string & {})> | undefined;
    "-webkit-border-image"?: import("csstype").Property.BorderImage | undefined;
    "-webkit-border-radius"?: import("csstype").Property.BorderRadius<0 | (string & {})> | undefined;
    "-webkit-column-rule"?: import("csstype").Property.ColumnRule<0 | (string & {})> | undefined;
    "-webkit-columns"?: import("csstype").Property.Columns<0 | (string & {})> | undefined;
    "-webkit-flex"?: import("csstype").Property.Flex<0 | (string & {})> | undefined;
    "-webkit-flex-flow"?: import("csstype").Property.FlexFlow | undefined;
    "-webkit-mask"?: import("csstype").Property.WebkitMask<0 | (string & {})> | undefined;
    "-webkit-mask-box-image"?: import("csstype").Property.MaskBorder | undefined;
    "-webkit-text-emphasis"?: import("csstype").Property.TextEmphasis | undefined;
    "-webkit-text-stroke"?: import("csstype").Property.WebkitTextStroke<0 | (string & {})> | undefined;
    "-webkit-transition"?: import("csstype").Property.Transition<string & {}> | undefined;
    azimuth?: import("csstype").Property.Azimuth | undefined;
    "box-align"?: import("csstype").Property.BoxAlign | undefined;
    "box-direction"?: import("csstype").Property.BoxDirection | undefined;
    "box-flex"?: import("csstype").Property.BoxFlex | undefined;
    "box-flex-group"?: import("csstype").Property.BoxFlexGroup | undefined;
    "box-lines"?: import("csstype").Property.BoxLines | undefined;
    "box-ordinal-group"?: import("csstype").Property.BoxOrdinalGroup | undefined;
    "box-orient"?: import("csstype").Property.BoxOrient | undefined;
    "box-pack"?: import("csstype").Property.BoxPack | undefined;
    clip?: import("csstype").Property.Clip | undefined;
    "grid-column-gap"?: import("csstype").Property.GridColumnGap<0 | (string & {})> | undefined;
    "grid-gap"?: import("csstype").Property.GridGap<0 | (string & {})> | undefined;
    "grid-row-gap"?: import("csstype").Property.GridRowGap<0 | (string & {})> | undefined;
    "ime-mode"?: import("csstype").Property.ImeMode | undefined;
    "offset-block"?: import("csstype").Property.InsetBlock<0 | (string & {})> | undefined;
    "offset-block-end"?: import("csstype").Property.InsetBlockEnd<0 | (string & {})> | undefined;
    "offset-block-start"?: import("csstype").Property.InsetBlockStart<0 | (string & {})> | undefined;
    "offset-inline"?: import("csstype").Property.InsetInline<0 | (string & {})> | undefined;
    "offset-inline-end"?: import("csstype").Property.InsetInlineEnd<0 | (string & {})> | undefined;
    "offset-inline-start"?: import("csstype").Property.InsetInlineStart<0 | (string & {})> | undefined;
    "scroll-snap-coordinate"?: import("csstype").Property.ScrollSnapCoordinate<0 | (string & {})> | undefined;
    "scroll-snap-destination"?: import("csstype").Property.ScrollSnapDestination<0 | (string & {})> | undefined;
    "scroll-snap-points-x"?: import("csstype").Property.ScrollSnapPointsX | undefined;
    "scroll-snap-points-y"?: import("csstype").Property.ScrollSnapPointsY | undefined;
    "scroll-snap-type-x"?: import("csstype").Property.ScrollSnapTypeX | undefined;
    "scroll-snap-type-y"?: import("csstype").Property.ScrollSnapTypeY | undefined;
    "-khtml-box-align"?: import("csstype").Property.BoxAlign | undefined;
    "-khtml-box-direction"?: import("csstype").Property.BoxDirection | undefined;
    "-khtml-box-flex"?: import("csstype").Property.BoxFlex | undefined;
    "-khtml-box-flex-group"?: import("csstype").Property.BoxFlexGroup | undefined;
    "-khtml-box-lines"?: import("csstype").Property.BoxLines | undefined;
    "-khtml-box-ordinal-group"?: import("csstype").Property.BoxOrdinalGroup | undefined;
    "-khtml-box-orient"?: import("csstype").Property.BoxOrient | undefined;
    "-khtml-box-pack"?: import("csstype").Property.BoxPack | undefined;
    "-khtml-line-break"?: import("csstype").Property.LineBreak | undefined;
    "-khtml-opacity"?: import("csstype").Property.Opacity | undefined;
    "-khtml-user-select"?: import("csstype").Property.UserSelect | undefined;
    "-moz-background-clip"?: import("csstype").Property.BackgroundClip | undefined;
    "-moz-background-inline-policy"?: import("csstype").Property.BoxDecorationBreak | undefined;
    "-moz-background-origin"?: import("csstype").Property.BackgroundOrigin | undefined;
    "-moz-background-size"?: import("csstype").Property.BackgroundSize<0 | (string & {})> | undefined;
    "-moz-binding"?: import("csstype").Property.MozBinding | undefined;
    "-moz-border-radius"?: import("csstype").Property.BorderRadius<0 | (string & {})> | undefined;
    "-moz-border-radius-bottomleft"?: import("csstype").Property.BorderBottomLeftRadius<0 | (string & {})> | undefined;
    "-moz-border-radius-bottomright"?: import("csstype").Property.BorderBottomRightRadius<0 | (string & {})> | undefined;
    "-moz-border-radius-topleft"?: import("csstype").Property.BorderTopLeftRadius<0 | (string & {})> | undefined;
    "-moz-border-radius-topright"?: import("csstype").Property.BorderTopRightRadius<0 | (string & {})> | undefined;
    "-moz-box-align"?: import("csstype").Property.BoxAlign | undefined;
    "-moz-box-direction"?: import("csstype").Property.BoxDirection | undefined;
    "-moz-box-flex"?: import("csstype").Property.BoxFlex | undefined;
    "-moz-box-ordinal-group"?: import("csstype").Property.BoxOrdinalGroup | undefined;
    "-moz-box-orient"?: import("csstype").Property.BoxOrient | undefined;
    "-moz-box-pack"?: import("csstype").Property.BoxPack | undefined;
    "-moz-box-shadow"?: import("csstype").Property.BoxShadow | undefined;
    "-moz-float-edge"?: import("csstype").Property.MozFloatEdge | undefined;
    "-moz-force-broken-image-icon"?: import("csstype").Property.MozForceBrokenImageIcon | undefined;
    "-moz-opacity"?: import("csstype").Property.Opacity | undefined;
    "-moz-outline"?: import("csstype").Property.Outline<0 | (string & {})> | undefined;
    "-moz-outline-color"?: import("csstype").Property.OutlineColor | undefined;
    "-moz-outline-radius"?: import("csstype").Property.MozOutlineRadius<0 | (string & {})> | undefined;
    "-moz-outline-radius-bottomleft"?: import("csstype").Property.MozOutlineRadiusBottomleft<0 | (string & {})> | undefined;
    "-moz-outline-radius-bottomright"?: import("csstype").Property.MozOutlineRadiusBottomright<0 | (string & {})> | undefined;
    "-moz-outline-radius-topleft"?: import("csstype").Property.MozOutlineRadiusTopleft<0 | (string & {})> | undefined;
    "-moz-outline-radius-topright"?: import("csstype").Property.MozOutlineRadiusTopright<0 | (string & {})> | undefined;
    "-moz-outline-style"?: import("csstype").Property.OutlineStyle | undefined;
    "-moz-outline-width"?: import("csstype").Property.OutlineWidth<0 | (string & {})> | undefined;
    "-moz-text-align-last"?: import("csstype").Property.TextAlignLast | undefined;
    "-moz-text-decoration-color"?: import("csstype").Property.TextDecorationColor | undefined;
    "-moz-text-decoration-line"?: import("csstype").Property.TextDecorationLine | undefined;
    "-moz-text-decoration-style"?: import("csstype").Property.TextDecorationStyle | undefined;
    "-moz-user-input"?: import("csstype").Property.MozUserInput | undefined;
    "-ms-ime-mode"?: import("csstype").Property.ImeMode | undefined;
    "-o-animation"?: import("csstype").Property.Animation<string & {}> | undefined;
    "-o-animation-delay"?: import("csstype").Property.AnimationDelay<string & {}> | undefined;
    "-o-animation-direction"?: import("csstype").Property.AnimationDirection | undefined;
    "-o-animation-duration"?: import("csstype").Property.AnimationDuration<string & {}> | undefined;
    "-o-animation-fill-mode"?: import("csstype").Property.AnimationFillMode | undefined;
    "-o-animation-iteration-count"?: import("csstype").Property.AnimationIterationCount | undefined;
    "-o-animation-name"?: import("csstype").Property.AnimationName | undefined;
    "-o-animation-play-state"?: import("csstype").Property.AnimationPlayState | undefined;
    "-o-animation-timing-function"?: import("csstype").Property.AnimationTimingFunction | undefined;
    "-o-background-size"?: import("csstype").Property.BackgroundSize<0 | (string & {})> | undefined;
    "-o-border-image"?: import("csstype").Property.BorderImage | undefined;
    "-o-object-fit"?: import("csstype").Property.ObjectFit | undefined;
    "-o-object-position"?: import("csstype").Property.ObjectPosition<0 | (string & {})> | undefined;
    "-o-tab-size"?: import("csstype").Property.TabSize<0 | (string & {})> | undefined;
    "-o-text-overflow"?: import("csstype").Property.TextOverflow | undefined;
    "-o-transform"?: import("csstype").Property.Transform | undefined;
    "-o-transform-origin"?: import("csstype").Property.TransformOrigin<0 | (string & {})> | undefined;
    "-o-transition"?: import("csstype").Property.Transition<string & {}> | undefined;
    "-o-transition-delay"?: import("csstype").Property.TransitionDelay<string & {}> | undefined;
    "-o-transition-duration"?: import("csstype").Property.TransitionDuration<string & {}> | undefined;
    "-o-transition-property"?: import("csstype").Property.TransitionProperty | undefined;
    "-o-transition-timing-function"?: import("csstype").Property.TransitionTimingFunction | undefined;
    "-webkit-box-align"?: import("csstype").Property.BoxAlign | undefined;
    "-webkit-box-direction"?: import("csstype").Property.BoxDirection | undefined;
    "-webkit-box-flex"?: import("csstype").Property.BoxFlex | undefined;
    "-webkit-box-flex-group"?: import("csstype").Property.BoxFlexGroup | undefined;
    "-webkit-box-lines"?: import("csstype").Property.BoxLines | undefined;
    "-webkit-box-ordinal-group"?: import("csstype").Property.BoxOrdinalGroup | undefined;
    "-webkit-box-orient"?: import("csstype").Property.BoxOrient | undefined;
    "-webkit-box-pack"?: import("csstype").Property.BoxPack | undefined;
    "-webkit-scroll-snap-points-x"?: import("csstype").Property.ScrollSnapPointsX | undefined;
    "-webkit-scroll-snap-points-y"?: import("csstype").Property.ScrollSnapPointsY | undefined;
    "alignment-baseline"?: import("csstype").Property.AlignmentBaseline | undefined;
    "baseline-shift"?: import("csstype").Property.BaselineShift<0 | (string & {})> | undefined;
    "clip-rule"?: import("csstype").Property.ClipRule | undefined;
    "color-interpolation"?: import("csstype").Property.ColorInterpolation | undefined;
    "color-rendering"?: import("csstype").Property.ColorRendering | undefined;
    "dominant-baseline"?: import("csstype").Property.DominantBaseline | undefined;
    fill?: import("csstype").Property.Fill | undefined;
    "fill-opacity"?: import("csstype").Property.FillOpacity | undefined;
    "fill-rule"?: import("csstype").Property.FillRule | undefined;
    "flood-color"?: import("csstype").Property.FloodColor | undefined;
    "flood-opacity"?: import("csstype").Property.FloodOpacity | undefined;
    "glyph-orientation-vertical"?: import("csstype").Property.GlyphOrientationVertical | undefined;
    "lighting-color"?: import("csstype").Property.LightingColor | undefined;
    marker?: import("csstype").Property.Marker | undefined;
    "marker-end"?: import("csstype").Property.MarkerEnd | undefined;
    "marker-mid"?: import("csstype").Property.MarkerMid | undefined;
    "marker-start"?: import("csstype").Property.MarkerStart | undefined;
    "shape-rendering"?: import("csstype").Property.ShapeRendering | undefined;
    "stop-color"?: import("csstype").Property.StopColor | undefined;
    "stop-opacity"?: import("csstype").Property.StopOpacity | undefined;
    stroke?: import("csstype").Property.Stroke | undefined;
    "stroke-dasharray"?: import("csstype").Property.StrokeDasharray<0 | (string & {})> | undefined;
    "stroke-dashoffset"?: import("csstype").Property.StrokeDashoffset<0 | (string & {})> | undefined;
    "stroke-linecap"?: import("csstype").Property.StrokeLinecap | undefined;
    "stroke-linejoin"?: import("csstype").Property.StrokeLinejoin | undefined;
    "stroke-miterlimit"?: import("csstype").Property.StrokeMiterlimit | undefined;
    "stroke-opacity"?: import("csstype").Property.StrokeOpacity | undefined;
    "stroke-width"?: import("csstype").Property.StrokeWidth<0 | (string & {})> | undefined;
    "text-anchor"?: import("csstype").Property.TextAnchor | undefined;
    "vector-effect"?: import("csstype").Property.VectorEffect | undefined;
};
